# Generated by Django 5.0.4 on 2024-05-02 04:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
